### ISSUE TITLE
AttributeError: 'TorchImageView' object has no attribute '_OpenGLFrame__context'

### ISSUE THREAD

**Issue by cf904c27** [harskish/ganspace#3]
the error is:

Loaded components for car from /home/jupyter/ganspace/cache/components/stylegan2-car_style_ipca_c80_n1000000.npz
Seed: 1116518040
GLX version: 0.0
Screen is  0
Xlib:  extension "GLX" missing on display ":20.0".
Number of FBconfigs 0
oh dear - visual does not match
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/opt/conda/lib/python3.7/site-packages/pyopengltk/base.py", line 29, in tkMap
    self.tkCreateContext()
  File "/opt/conda/lib/python3.7/site-packages/pyopengltk/linux.py", line 103, in tkCreateContext
    cfgs[best],
ValueError: NULL pointer access
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/opt/conda/lib/python3.7/site-packages/pyopengltk/base.py", line 74, in tkExpose
    self._display()
  File "/opt/conda/lib/python3.7/site-packages/pyopengltk/base.py", line 97, in _display
    self.tkMakeCurrent()
  File "/opt/conda/lib/python3.7/site-packages/pyopengltk/linux.py", line 156, in tkMakeCurrent
    GLX.glXMakeCurrent(self.__window, self._wid, self.__context)
AttributeError: 'TorchImageView' object has no attribute '_OpenGLFrame__context'
Traceback (most recent call last):
  File "interactive.py", line 651, in <module>
    app.update()
  File "/home/jupyter/ganspace/TkTorchWindow.py", line 195, in update
    self.tkMakeCurrent()
  File "/opt/conda/lib/python3.7/site-packages/pyopengltk/linux.py", line 156, in tkMakeCurrent
    GLX.glXMakeCurrent(self.__window, self._wid, self.__context)
AttributeError: 'TorchImageView' object has no attribute '_OpenGLFrame__context'

Can you help?

**Comment by harskish** [comment]
This sounds like an OpenGL issue. Perhaps one of these links will help:

https://bbs.archlinux.org/viewtopic.php?id=213076
https://github.com/Bumblebee-Project/Bumblebee/issues/748
https://unix.stackexchange.com/questions/254377/xlib-extension-glx-missing-with-an-nvidia-card-and-on-board-graphics

**Comment by gingergenius** [comment]
I have the exact same error on an Azure Ubuntu VM except the line "Xlib: extension "GLX" missing on display ":20.0"." is missing from the output. 
@cf904c27 did you solve your issue? 

Should I install bumblebee?
