### ISSUE TITLE
ModuleNotFoundError: No module named 'model'

### ISSUE THREAD

**Issue by HangAround47** [harskish/ganspace#30]
Traceback (most recent call last):
  File "interactive.py", line 22, in <module>
    from models import get_instrumented_model
  File "C:\Users\Creator\Downloads\ganspace-master\ganspace-master\models\__init__.py", line 11, in <module>
    from .wrappers import *
  File "C:\Users\Creator\Downloads\ganspace-master\ganspace-master\models\wrappers.py", line 23, in <module>
    from . import stylegan2
  File "C:\Users\Creator\Downloads\ganspace-master\ganspace-master\models\stylegan2\__init__.py", line 14, in <module>
    from model import Generator
ModuleNotFoundError: No module named 'model'

Does my installation fail on windows?

**Comment by HangAround47** [comment]
May be due to the need to copy
All files of stylegan2-pytorch to ./models/stylegan2
