### ISSUE TITLE
Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by HangAround47** [harskish/ganspace#31]
Hi!
I still cannot run successfully under win10, do I need to delete VS2019?
Thank you！

python interactive.py
C:\Users\Creator\miniconda3\lib\site-packages\torch\utils\cpp_extension.py:237: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
Traceback (most recent call last):
  File "C:\Users\Creator\miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "C:\Users\Creator\miniconda3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "interactive.py", line 23, in <module>
    from models import get_instrumented_model
  File "C:\MyWork\My_GAN_Work\ganspace-master\models\__init__.py", line 11, in <module>
    from .wrappers import *
  File "C:\MyWork\My_GAN_Work\ganspace-master\models\wrappers.py", line 23, in <module>
    from . import stylegan2
  File "C:\MyWork\My_GAN_Work\ganspace-master\models\stylegan2\__init__.py", line 14, in <module>
    from model import Generator
  File "C:\MyWork\My_GAN_Work\ganspace-master\models\stylegan2\stylegan2-pytorch\model.py", line 11, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "C:\MyWork\My_GAN_Work\ganspace-master\models\stylegan2\stylegan2-pytorch\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "C:\MyWork\My_GAN_Work\ganspace-master\models\stylegan2\stylegan2-pytorch\op\fused_act.py", line 15, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "C:\Users\Creator\miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 898, in load
    is_python_module)
  File "C:\Users\Creator\miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1086, in _jit_compile
    with_cuda=with_cuda)
  File "C:\Users\Creator\miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1186, in _write_ninja_file_and_build_library
    error_prefix="Error building extension '{}'".format(name))
  File "C:\Users\Creator\miniconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1412, in _run_ninja_build
    message += ": {}".format(error.output.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 1289: invalid continuation byte

**Comment by HangAround47** [comment]
The easiest way is to use the English version of VS 2017

**Comment by milky245** [comment]
Hello, I have the same problem as you, and the error message is the same. I'm using VS2022, but I still have a problem after changing the language pack to English version. Do you know how to solve it? Thanks.

File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\torch\utils\cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "C:\Users\ASUS\.conda\envs\GAN_practice\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

File "C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\torch\utils\cpp_extension.py", line 1554, in _run_ninja_build
    message += ": {}".format(error.output.decode())  # type: ignore
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 18: invalid start byte
