### ISSUE TITLE
ModuleNotFoundError: No module named 'model'

### ISSUE THREAD

**Issue by gaurav19063** [harskish/ganspace#45]
I am running following Syntex to run in colab

# Explore StyleGAN2 ffhq in W space

`!python interactive.py --model=StyleGAN2 --class=ffhq --layer=style --use_w -n=1_000_000 -b=10_000`

But I am getting model module not found error.

Traceback (most recent call last):
  File "interactive.py", line 22, in <module>
    from models import get_instrumented_model
  File "/content/ganspace/models/__init__.py", line 11, in <module>
    from .wrappers import *
  File "/content/ganspace/models/wrappers.py", line 23, in <module>
    from . import stylegan2
  File "/content/ganspace/models/stylegan2/__init__.py", line 14, in <module>
    from model import Generator

ModuleNotFoundError: No module named 'model'

Any Suggested fix or any help?

**Comment by gaurav19063** [comment]
Has been fixed in #10
