### ISSUE TITLE
missing strided_style method ? 

### ISSUE THREAD

**Issue by fouratthamri** [harskish/ganspace#5]
I didn't find any explanation to this error since I did not find where strided_style is defined. here's the error: 

`
Traceback (most recent call last):
  File "interactive.py", line 643, in <module>
    setup_model()
  File "interactive.py", line 152, in setup_model
    load_components(class_name, inst)
  File "interactive.py", line 57, in load_components
    dump_name = get_or_compute(config, inst)
  File "/home/fouratthamri/Documents/ganspace/ganspace/decomposition.py", line 363, in get_or_compute
    return _compute(submit_config, config, model, force_recompute)
  File "/home/fouratthamri/Documents/ganspace/ganspace/decomposition.py", line 394, in _compute
    compute(config, dump_path, model)
  File "/home/fouratthamri/Documents/ganspace/ganspace/decomposition.py", line 178, in compute
    model.partial_forward(model.sample_latent(1), layer_key)
  File "/home/fouratthamri/Documents/ganspace/ganspace/models/wrappers.py", line 202, in partial_forward
    if len(styles) == 1:
  File "/home/fouratthamri/anaconda3/envs/ganspace/lib/python3.7/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'Generator' object has no attribute 'strided_style'

`

**Comment by fouratthamri** [comment]
I fixed this by using your fork of the stylegan2 PyTorch repo. But please update the GanSpace repo so both of your features and Rosinality's ones become unified in a single repo, because I was very confused.
