### ISSUE TITLE
googledrive not downloading ,m pleas sepcify instructions where model files should be for manual download 

### ISSUE THREAD

**Issue by 2blackbar** [harskish/ganspace#57]
StyleGAN2: Optimized CUDA op FusedLeakyReLU not available, using native PyTorch fallback.
StyleGAN2: Optimized CUDA op UpFirDn2d not available, using native PyTorch fallback.
Downloading https://drive.google.com/uc?export=download&id=1FJRwzAkV-XWbxgTwxEmEACvuqF5DsBiV
Traceback (most recent call last):
  File "interactive.py", line 644, in <module>
    setup_model()
  File "interactive.py", line 143, in setup_model
    inst = get_instrumented_model(model_name, class_name, layer_name, torch.device('cuda'), use_w=args.use_w)
  File "C:\Users\BAZO\anaconda3\envs\ganspace\lib\functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\BAZO\ganspace\models\wrappers.py", line 695, in get_instrumented_model
    model = get_model(name, output_class, device, **kwargs)
  File "C:\Users\BAZO\anaconda3\envs\ganspace\lib\functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\BAZO\ganspace\models\wrappers.py", line 680, in get_model
    model = StyleGAN2(device, class_name=output_class)
  File "C:\Users\BAZO\ganspace\models\wrappers.py", line 125, in __init__
    self.load_model()
  File "C:\Users\BAZO\ganspace\models\wrappers.py", line 161, in load_model
    self.download_checkpoint(checkpoint)
  File "C:\Users\BAZO\ganspace\models\wrappers.py", line 151, in download_checkpoint
    download_ckpt(url, outfile)
  File "C:\Users\BAZO\ganspace\utils.py", line 86, in download_ckpt
    download_google_drive(url, output_name)
  File "C:\Users\BAZO\ganspace\utils.py", line 53, in download_google_drive
    assert tokens is not None, 'Could not extract token from response'
AssertionError: Could not extract token from response

**Comment by 2blackbar** [comment]
cmon people , basic colab stuff isnt working , sure its cute we have to downloasd manually but where and why renaming ? /usr/local/lib/python3.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1UlDmJVLLnBD9SnLSMXeiZRO6g-OMQCA_
